### ISSUE TITLE
[Question] Android

### ISSUE THREAD

**Issue by Drjacky** [AleksaMCode/WiFi-password-stealer#6]
Do you have/(or know the possibility of) the payload to get the Wi-Fi password from an Android device connected to that network?

**Comment by AleksaMCode** [comment]
Do you mean a BadUSB that could be used to execute commands on an Android device? I don't have that kind of payload, but you could always create a Wi-Fi QR code on your device. Most Android devices don't have a bash interpreter, so you can't just plug in a USB and execute commands to get the Wi-Fi passwords. In order to execute commands, you'll probably need a rooted device.
